kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: flask-microservice-pvc
  namespace: flask-microservice-namespace
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi # should not be more than what pv has